qmk/qmk_toolbox

osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/USB.cs
Add support Adafruit Feather BLE 32u4, Issue #10
=> Add support for Adafruit FeatherBLE 32u4

windows/QMK Toolbox/MainWindow.cs
issue: #37
We can't download keymap file from `qmk.fm`, SSL/TLS error has thrown.
Currently, `qmk.fm` uses `TLS 1.2`, and HTTP access has redirected to HTTPS.
`WebClient` accesses HTTPS sites using `TLS 1.0` by default, that causes SSL/TLS error.
- Enable `TLS 1.2`
- Modify URLs of `qmk.fm` with HTTPS
- Add error handling in `LoadKeyboardList` method
- Use `using` statement for `WebClient`
=> Use TLS1.2 when download files from qmk.fm

.gitignore
=> Add .DS_Store and xcworkspace to gitignore

common/mcu-list.txt, osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/USB.m, osx/qmk_toolbox/main.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs, windows/QMK Toolbox/USB.cs, windows/QMK Toolbox/mcu-list.txt
Related issue(s) (if any):
Changes:
=> Add USBAsp ISP and 328p mcu

readme.md
Tapping `caskroom/drivers` still works for backward compatibility, but Casks are now part of Homebrew proper and we might as well encourage the new name.
*
=> Update Homebrew installation commands

windows/install_compiler.iss, windows/release.bat
Missed a version or two.  
Also, cleanup Windows script to make sure versions increment properly (eg, I don't know why it didn't)
=> Additional changes to version increment

windows/QMK Toolbox/Flashing.cs
=> WINDOWS: Fix avrdude command for usbasp

windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
For the sake of my, and everyone else's, eyes 😄
I think the red text could be lightened a bit too, to improve the contrast...
*
=> [Windows] Change log text box font to Consolas

common/mcu-list.txt
=> Add ATmega32A to MCU list

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/main.m, readme.md, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs
Improved the readme a bit, made the "Supported bootloaders" list more consistent among the various places it lives.
*
=> Tidy up flasher list messages and readme

windows/QMK Toolbox/MainWindow.cs
This should finally fix the driver installation prompt properly... now it actually runs instead of perpetually erroring out and asking to retry.
*
=> Invert File.Exists check for qmk_driver_installer.exe

readme.md
There should only be one H1 heading.
*
=> Fix readme headings

readme.md
=> Corrected Spelling

windows/QMK Toolbox/MainWindow.Designer.cs
I bungled the merge resolution a bit. The button was still in its old position.
*
=> Correct EEPROM button location

osx/QMK Toolbox.pkgproj, osx/qmk_toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/install_compiler.iss
=> Increment version to 0.0.15

windows/QMK Toolbox/MainWindow.Designer.cs
=> Include both hex and bin in open dialog file filter

windows/QMK Toolbox/BetterComboBox.cs, windows/QMK Toolbox/MainWindow.cs
This should be handled by the ComboBox subclass, not the MainWindow code.
*
=> Move BetterComboBox delete key handler into the class itself

windows/QMK Toolbox/MainWindow.cs
This class doesn't do anything.
*
=> Remove UsbDeviceInfo

windows/QMK Toolbox/BetterComboBox.cs
=> Fix typo preventing build

readme.md
=> Link QMK Docs for Zadig in main readme

windows/install_compiler.iss
Various tweaks to help make it more polished. In the process I discovered the icon file is missing the 32x32 size, so we get this gross thing sometimes:
@jackhumbert would you be able to provide an updated icon?
*
=> Update Inno Setup script

osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs
=> Specify MCU dropdown as AVR only

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
=> Call ResetAtmelSamBa() from Reset()

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
USBAsp doesn't have/use a serial port...
*
=> Fix USBAsp Clear EEPROM command line

windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
Same as https://github.com/qmk/qmk_toolbox/pull/177 and https://github.com/qmk/qmk_toolbox/pull/178, but for Windows.
*
=> [Windows] Add new blank option as default keyboard, fix alignments

osx/qmk_toolbox/AppDelegate.m, windows/QMK Toolbox/MainWindow.cs
Add version number printout to console log, which can be handy for us to make sure users are on the correct version while trying to assist them.
*
=> Add version number

.gitignore, osx/qmk_toolbox/HID.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.cs
Hopefully, this will make it clearer that these messages do not list all QMK keyboards that are connected, only the ones with the Console feature enabled.
*
=> Update console detection/list messages for clarification

.github/workflows/build.yml, osx/build_release.command, readme.md
* Builds osx/windows for PR/master and attaches build artifacts
* <https://github.com/zvecr/qmk_toolbox/actions/runs/93646898>
* used for release, but could be used for review? 
* Open a release on github and it will automagically build and upload artifacts
* <https://github.com/zvecr/qmk_toolbox/releases/tag/v1.0.2>
* handle version number ?
* sign files ?
=> Initial stab at a CI and release workflow

osx/qmk_toolbox/USB.m, windows/QMK Toolbox/USB.cs
A batch of Pro Micros I received had a VID/PID of 2A03/0036, so just adding support for it by adding the 2A03 VID
*
=> Add Caterina VID for dog hunter AG

.github/workflows/build.yml
Looks like i got the wrong event, created is triggered when you draft a release not when you hit the magic "publish" button.
*
=> Fix release build event

readme.md
To match what the UI and output looks like now.
*
=> Update readme images

windows/QMK Toolbox/USB.cs
Allows for easier diagnosis of wrong driver installation :)
*
=> [Windows] Print bootloader drivers

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
Same as qmk/qmk_firmware#10070.
* Fixes #189
=> Use the force when flashing with dfu-programmer

osx/QMK Toolbox.xcodeproj/project.pbxproj, osx/QMK Toolbox.xcodeproj/xcshareddata/xcschemes/QMK Toolbox.xcscheme
Set project version to 11.4 and hit "Update to recommended settings" nag, which changed the `CODE_SIGN_IDENTITY` lines.
*
=> Update more Xcode stuff

osx/QMK Toolbox.pkgproj, osx/qmk_toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/install_compiler.iss
=> Increment version to 0.0.20

windows/QMK Toolbox/MainWindow.cs
This prevents the user being prompted to install drivers when first running a new version, even if they have already been asked.
*
=> [Windows] Upgrade settings on version bump

windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
Be more specific when referring to this bootloader. I think I must have missed this when doing the macOS side of things in #208.
*
=> [Windows] Change `Dfu` to `AtmelDfu`

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
=> [Windows] Change `Stm32` to `Stm32Dfu`

.github/workflows/build.yml
Last build failed due to `add-path` being deprecated.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
*
=> Update setup-msbuild to 1.0.2

readme.md, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs, windows/QMK Toolbox/USB.cs, windows/QMK Toolbox/drivers.txt
Adds support for the STM32duino bootloader, VID=0x1eaf, PID=0x0003.
=> Add support for STM32duino DFU bootloader.

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/Printing.m, osx/qmk_toolbox/USB.h, osx/qmk_toolbox/USB.m, osx/qmk_toolbox/main.m, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Printing.cs, windows/QMK Toolbox/Program.cs
Since the QMK CLI does a better job of this (and will actually be on the `PATH`).
Also fixed a couple related things on the Windows side:
- Added a `try...finally` around the `Application.Run`, this should release the mutex even if the Toolbox crashes
- Improved the file passed in stuff so that it actually works (seems like it was failing due to the `qmk_toolbox/` directory not existing, so double clicking on a .hex file with the file association applied didn't work)
- Made the existing window focus properly when opening a firmware file or trying to run the Toolbox again
*
=> Remove command line code

.github/workflows/build.yml
```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
*
=> Fix brew workflow

osx/QMK Toolbox.pkgproj, osx/qmk_toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/install_compiler.iss
=> Increment version to 0.0.21

common/mcu-list.txt
=> Add AT90USB162 to mcu-list.txt

windows/QMK Toolbox/MainWindow.Designer.cs
=> [Windows] Fix tab order

macos/QMK Toolbox/AppDelegate.h, macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/Base.lproj/MainMenu.xib
Added menu items for Flash, Exit DFU, EEPROM (including handedness setting, but not sure yet how that will work out) and Auto-Flash.
*
=> [macOS] More menu items

macos/QMK Toolbox.pkgproj, macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/Info.plist, readme.md, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/QMK Toolbox/Properties/DataSources/WindowState.datasource, windows/install_compiler.iss
Due to the significant improvements this round, I think a minor rev bump is in order.
Also included in this PR are some updates to the supported bootloaders list, and new screenshots for the readme.
*
=> Increment version to 0.1.0

macos/QMK Toolbox.pkgproj, macos/QMK Toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/QMK Toolbox/Properties/DataSources/WindowState.datasource, windows/install_compiler.iss
This release fixes a couple of bugs:
#295 #293 
*
=> Increment version to 0.1.1

windows/QMK Toolbox/Helpers/DriverInstaller.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj
More moving stuff out of MainWindow.cs to be handled by a separate class.
*
=> [Windows] Driver installer refactor

macos/QMK Toolbox/AppDelegate.h, macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/Constants.m, macos/QMK Toolbox/Flashing.h, macos/QMK Toolbox/Flashing.m, macos/QMK Toolbox/HIDConsole/HIDConsoleDevice.h, macos/QMK Toolbox/HIDConsole/HIDConsoleListener.h, macos/QMK Toolbox/Printing.h, macos/QMK Toolbox/QMKWindow.h, macos/QMK Toolbox/QMKWindow.m, macos/QMK Toolbox/USB.h, macos/QMK Toolbox/USB.m
`#include` -> `#import` and removed unneeded ones.
*
=> [macOS] Tidy up imports

macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/QMKWindow.h, macos/QMK Toolbox/QMKWindow.m
`registerForDraggedTypes` can be called from the NSWindow `awakeFromNib`, eliminating the need for a separate `setup` method.
*
=> [macOS] Move drag-drop registration

windows/QMK Toolbox/MainWindow.Designer.cs
=> [Windows] UI updates

macos/QMK Toolbox/USB/Bootloader/LUFAMSDevice.m
=> [macOS] LUFA-MS: return early on error

readme.md
Because the Toolbox uses flashing binaries borrowed from the Homebrew bottles for Catalina, and the deployment target is set to 10.15.
For Windows, the specified version is not a hard limit, it mainly depends on whether .NET Framework 4.8 is installed. Per the link, it is only installed by default after 1809, but should still work (untested) all the way down to Windows 7.
*
=> Add system requirements to readme

windows/QMK Toolbox/QMK Toolbox.csproj
=> [Windows] Update Nuget packages

LICENSE.md, macos/QMK Toolbox.pkgproj, macos/QMK Toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs
Probably should have remembered this before the release...
=> Update copyright year

macos/QMK Toolbox/AppDelegate.m, windows/QMK Toolbox/MainWindow.cs
=> Fix handedness .eep filenames

macos/QMK Toolbox/AppDelegate.m, windows/QMK Toolbox/MainWindow.cs
I knew there was something I'd forgotten...
* Fixes #364
=> Wire up auto-flash again

windows/QMK Toolbox/QMK Toolbox.csproj
Since we no longer do anything with zip files.
*
=> [Windows] Remove unnecessary System.IO.Compression.Filesystem ref

macos/QMK Toolbox.pkgproj, macos/QMK Toolbox/Info.plist, windows/QMK Toolbox/Properties/AssemblyInfo.cs, windows/QMK Toolbox/Properties/DataSources/WindowState.datasource, windows/install_compiler.iss
Mainly for autoflash, next minor release may be a while.
=> Increment version to 0.2.2

macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox.xcodeproj/xcshareddata/xcschemes/QMK Toolbox.xcscheme, macos/QMK Toolbox/Base.lproj/MainMenu.xib
Sorted some entries, let Xcode update some stuff, removed IOKit framework (pretty sure it isn't  explicitly needed?).
*
=> [macOS] Tidy up pbxproj a little

windows/QMK Toolbox/QMK Toolbox.csproj
On 64-bit Windows the Toolbox should run as a 64-bit application.
It's possible this fixes #383. Will need testing.
*
=> [Windows] Do not prefer 32-bit

.github/labeler.yml, .github/workflows/labeler.yml
=> Autolabel Windows and macOS changes

.github/workflows/build.yml
=> Run `brew update` during macOS build workflow

.github/workflows/labeler.yml
=> Fix autolabel workflow

.github/labeler.yml, .github/workflows/labeler.yml
=> Update labeler workflow

macos/QMK Toolbox/MainViewController.swift, windows/QMK Toolbox/MainWindow.cs
Making this a little more obvious than some of the flashing tools do.
*
=> Check file exists before attempting flash

LICENSE.md, macos/QMK Toolbox.pkgproj, macos/QMK Toolbox/Info.plist, windows/QMK Toolbox/Properties/DataSources/WindowState.datasource, windows/QMK Toolbox/QMK Toolbox.csproj, windows/install_compiler.iss
New release has been long overdue.
=> Increment version to 0.3.0

readme.md, windows/QMK Toolbox/QMK Toolbox.csproj
Also fixed version number display on Windows (apparently due to a breaking change, it now also shows the Git revision).
*
=> Update readme screenshots

readme.md
=> Update HID Console screenshot

readme.md
The GitHub releases assets listing can be a little confusing for some users.
*
=> Add friendlier links to latest release in readme

windows/QMK Toolbox/MainWindow.cs
Trying to figure out what the deal is here.
#442
*
=> [Windows] Catch COMException on load

macos/QMK Toolbox/Base.lproj/Main.storyboard, windows/QMK Toolbox/KeyTester/KeyTesterWindow.Designer.cs
Changed arrow key glyphs to use bigger triangles.
On Windows, updated numpad section + volume keys.
*
=> Minor tweaks to key tester labels

windows/QMK Toolbox/AboutBox.cs
Fixes #487
Passing the URL directly to `Process.Start()` apparently does not work anymore.
https://stackoverflow.com/questions/71977866/c-sharp-net-6-how-to-open-a-link-in-default-browser
*
=> Fix about box link
