windows/QMK Toolbox/Form1.cs
A simple typo in the message that appears when you downloaded a .hex file and it was saved.
=> Fix typo in file save message

readme.md
As of caskroom/homebrew-drivers#310 you can now install QMK Toolbox on macOS using Homebrew-Cask :)
=> Add info about Homebrew

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
- dfu-util requires "leave" after the starting address in order to exit the bootloader after the flashing has finished
- Please compile this real quick as I am unable to. Probably missing some dipendencies (or I am just lazy:))
=> STM32 flashing now exits bootloader

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
Related issue(s) (if any):
Fixes #63.
Changes:
Added a check to see if the filename ends with ".bin" before trying to use dfu-util.
I can't test this as I don't have an STM32 keyboard, but the logic is pretty simple and I'm reasonably confident it does the right thing. Testers appreciated, of course.
=> Check for .bin extension before attempting flash with dfu-util

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Info.plist
Fixes #31.
When opening .hex, .bin or .qmk files from outside of the Toolbox, `setFilePath` wants a filename prepended with either `file://` or `qmk:`, which `URLWithString` doesn't provide, so we should use `fileURLWithPath` here. Now the file path text box populates 👍
By default .bin has a UTI of [`com.apple.macbinary-archive`](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) and opens with Archive Utility, so instead of creating a new UTI we have to use that one.
=> [macOS] Allow firmware files to be opened directly

.github/ISSUE_TEMPLATE/blank.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Making the PR and issue templates for the Toolbox repo look more like the templates for the firmware repo, and tidying them away in `.github/`.
=> Move PR/issue templates under .github/ and flesh them out a bit more

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
dfu-programmer will fail to write to EEPROM citing memory not blank, so we need to skip that check.
Reportedly not working with or without `--force` on ATmega32U2 (@drashna).
*
=> Add --force flag to DFU EEPROM reset

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/MainWindow.resx
Right clicking on the log output text box gives you:
Which will empty it out.
~Windows-only ATM since I have no Xcode to hand. I'll add it to this PR tomorrow.~ Done
*
=> Add a button to clear the log output text box

osx/qmk_toolbox/AppDelegate.m
The first thing the Toolbox does when a firmware file is opened is convert its path to an `NSURL`. This has the side effect of percent encoding it. Reasonable, since it *is* a URL, but we don't want it as it just gets passed directly to the flasher tools.
* Fixes #87
=> [macOS] Fix loading file:// paths with spaces

osx/qmk_toolbox/USB.m
`/dev/cu.Bluetooth-Incoming-Port` pops up frequently when trying to connect/detect a stock Pro Micro. Ignore this port during the port scan so that the correct device can be found. 
*
=> Ignore bluetooth modem

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
According to the [USBAspLoader readme](https://github.com/baerwolf/USBaspLoader), this flasher *does* support resetting the EEPROM (though it seems the functionality may not be compiled in by default?).
*
=> Allow EEPROM reset with USBAsp flasher

osx/qmk_toolbox/HID.m
Noticed that the VID and PID are not displayed correctly for the blue HID messages.
*
=> [macOS] Fix VID/PID for HID (dis)connect messages

windows/QMK Toolbox/MainWindow.Designer.cs
PR #29 almost had it, but the `MainWindow_Shown()` handler wasn't hooked up to the `Shown` property, so it never prompted on first run.
*
=> Add MainWindow_Shown handler so the driver installation prompt appears

windows/QMK Toolbox/MainWindow.cs
Pressing the Flash button, for me, throws the following exception:
Evidently, it only happens sometimes, because there are not a ton of complaints about it.
Since all we need is to read the values of the path/MCU boxes, we can just store them in variables first, and look at *those*.
The same thing is not necessary for the reset/EEPROM buttons (at present) because they do not create a separate thread. Keeping the form responsive is less critical for those, they typically don't take that much time compared to erasing and flashing.
* I thought there was at least one report in the issue list, but all I can find are macOS crashes and driver-not-installed related crashes on Windows. 🤷‍♂
=> [Windows] Don't access UI controls in child thread when flashing

osx/qmk_toolbox/USB.m
Instead of ignoring all devices containing the word `Bluetooth`, we should be ignoring ones that *don't* contain the word `usbmodem`.
* Fixes #109 
* Possibly #111 ?
=> Filter out more non-Caterina devices

common/avrdude.conf, common/mcu-list.txt, osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/App.config, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Properties/Settings.Designer.cs, windows/QMK Toolbox/Properties/Settings.settings
- The MCU dropdown now properly remembers the last one selected, and provides a default on first run (`atmega32u4`) without relying on the assumption that it's the first entry
- The dropdown has also been changed to not be editable, to prevent users trying to empty it to flash ARM boards
- Added some missing MCUs (16U4, USB64) and sorted the list alphabetically, now that we can 😁
* Fixes #116
=> MCU box improvements

osx/qmk_toolbox/Printing.m
On macOS 10.15, flashing (at least with `dfu-programmer`) succeeds, but the Toolbox crashes immediately afterwards. For whatever reason we're getting zero-length NSData from the pipe, which I guess become zero-length NSStrings (see Flashing.m, `runProcess:withArgs`).
Either way, `[str characterAtIndex:[str length] - 1]` is bad unless we sanity check for at least one character.
*
=> Fix crashing after flash on Catalina

osx/README.md, osx/qmk_toolbox/USB.m
On my setup (MacBook Pro (Retina, 15-inch, Mid 2015) ; Mojave , qmk toolbox 0.0.13 (1) ), programming a pro micro device (caterina bootloader) didn't work. When pressing the reset button, qmk toolbox gave 
```
*** Caterina device disconnected
*** Caterina device connected
No modem port found, try again.
```
But looking at the /dev directory, I did see the `/dev/cu.usbmodem14101` appear.
I suspect that there is some delay in the creation of the /dev/cu.* device for some reason.
Increasing the delay fixed the issue on my machine, now I can flash my pro micro reliably.
```
*** Caterina device connected
Found port: /dev/cu.usbmodem14101
```
While attempting to build qmk configurator I also noticed that the documentation wasn't entirely accurate, so I fixed that up too.
=> Better detection of pro micro device on macos X

windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/USB.cs
The third number shown in the "device connected/disconnected" messages should be the device revision - this should be a more reliable method of grabbing that. I'm hoping this will allow us to detect QMK-DFU vs Atmel DFU and not have to do a full chip erase to clear the EEPROM, by setting the revision to something like the Unicode codepoint for Ψ (03A8). Also some various tweaks to clean up my work tree. :)
* Fixes #61
=> Bootloader detection improvements

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
Even though "clearing" is not *exactly* what the button does, it's probably a good idea to differentiate it from the Reset button that exits the bootloader.
*
=> Rename Reset EEPROM button to Clear EEPROM

windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs, windows/QMK Toolbox/USB.cs
This was due to me changing what information `deviceId` held in #129, and not realising this gets passed to `GetComPort()` 🤦‍♂ Since it no longer matched up with the `PNPDeviceId` associated with the COM port, nothing would be found. Instead let's just give `GetComPort()` the entire object so it can extract whatever it needs.
* Fixes #60
=> Send ManagementBaseObject instance to GetComPort()

osx/qmk_toolbox/AppDelegate.m, windows/QMK Toolbox/MainWindow.cs
Replaces the `.hex` extension with `.bin` if the attempt to download the former failed. Bit of a hack, but it works 👍
* Fixes #126
* Closes #62
=> Precompiled firmware download: try .bin if .hex not found

osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs
It's completely useless, and probably confusing for users. A better solution to the "multiple bootloader devices connected" situation would be to have a dropdown to select which one to operate on.
*
=> Remove "enabled flashers" box

windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
Removed the "jump to bootloader" button, as it doesn't work, and if it did, it'd be a security issue (see https://github.com/qmk/qmk_firmware/pull/7456). Similar goes for the "say hello" button, and again users are probably confused as to what it's for.
Moved the EEPROM clear button to the left side to match the macOS app.
*
=> Remove "Jump to bootloader" button

common/avrdude.conf
It turns out [avrdude does a `strcasecmp()`](http://svn.savannah.gnu.org/viewvc/avrdude/trunk/avrdude/avrpart.c?revision=1428&view=markup#l518) on the `-p` argument against both the part ID and description to figure out what the MCU is, so we can undo all of the ID changes, except for the 32A which needs to be a child part of the ATmega32. Now this file is much closer to the shipped version.
*
=> Put back original avrdude.conf part IDs

osx/QMK Toolbox.xcodeproj/project.pbxproj
As well as not being executable the reference to it in the pbxproj was different to the references for avrdude, dfu-programmer etc.
* Fixes #152 (properly this time)
=> Fix path to mdloader in Xcode project file

windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
Since it currently only prompts on first run and never again (until you update to a new version), added a way to run it (without the prompt) after the fact, if you accidentally clicked No.
*
=> [Windows] Add a menu item to retrigger driver install

windows/QMK Toolbox/USB.cs
Bug I struck while debugging -- in some cases it seems that when handling a device event, no `HardwareID` is specified.
=> Fix bug where disconnecting a device didn't supply a hardware ID

windows/QMK Toolbox/MainWindow.cs
For the STM32 bootloader, Windows may automatically download the STTub30 driver (DfuSe/"STM Device in DFU mode"). The driver installer needs to forcefully override it, as dfu-util will only flash with the WinUSB driver.
*
=> Set --force flag for driver installation

osx/qmk_toolbox/Base.lproj/MainMenu.xib
Now that the "Flashers enabled" box has been removed, expand the keyboard/keymap loader box to show more of the keyboard box, as text in the box can't be fully seen. Also fixes a few alignments of buttons and ambiguously placed items.
Current screen:
Revised screen:
*
=> [Mac] Increase Load box width, Fix alignments

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib
To prevent people from accidentally load the 1up keyboard, add a new default that can't be loaded.
Somewhat relates to https://github.com/qmk/qmk_toolbox/issues/176
*
=> [Mac] Add new blank option as default keyboard

osx/qmk_toolbox/Flashing.m, windows/QMK Toolbox/Flashing.cs
Rollbacks the removal of the erase command done in https://github.com/qmk/qmk_toolbox/pull/75 and adds a message to remind user to reflash firmware.
* https://github.com/qmk/qmk_toolbox/issues/97
=> Erase before clearing EEPROM

windows/QMK Toolbox/MainWindow.cs
Some devices, like the XD002 keyboard with the factory firmware, have HID report descriptors which do not declare any input reports.  If such HID descriptor additionally had the vendor-defined page and usage codes which correspond to the HID console, QMK Toolbox tried to use that HID interface as a HID console, and an attempt to read the nonexistent input report caused a crash inside HidLibrary; this made using QMK Toolbox impossible when a device with such HID report descriptor is connected.
Add a check for a non-zero input report size to `GetListableDevices()` to prevent the attempt to use a HID interface without any input repors as a HID console.
The problematic HID report descriptor from the XD002 firmware is probably [this one](https://github.com/panhao4812/Attiny85_vusb_pad_test/blob …
=> [Windows] Fix crash when a HID device has no input reports

windows/QMK Toolbox/drivers.txt
The Toolbox can currently flash USBAspLoader devices with the libusb0 driver set, however the MSYS2 avrdude cannot, so this should be updated to match.
*
=> Use libusbK driver for USBAspLoader

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/USB.h, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
- Renamed `CaterinaPort` to `serialPort`/`ComPort` as it's used for more than just Caterina
- Clarified some of the "chipset" enum names (eg. "FeatherBLE32u4" -> "AdafruitVID")
- Gave macOS some friendly names to use for each bootloader type (otherwise things like "AtmelDFU" would be displayed)
- Improved detection of serial devices on Windows -- this is where the meat of this PR is. I've added the function `IsSerialDevice()` which looks at the Compatible IDs of the device to check whether it has the USB class 0x02, subclass 0x02 which denotes a CDC-ACM device. That still wasn't enough though, as the Arduino firmware presents a CDC-ACM serial port as well. But, there are specific PIDs used by the various known Caterina bootloaders. For example 0037 is the Arduino Micro Caterina …
=> Improve detection and filtering of serial devices for Caterina

windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs
Currently BootloadHID devices must be flashed by first resetting the board, then starting Toolbox. This is because the WMI query to detect creation/deletion of PNPEntity objects apparently returns more than one result (the HID device and the USB device) but there seems to be no way to get at the next one(s) (see https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/wmi-activity-event-5858-logged-with-resultcode-0x80041032). The ManagementEventWatcher only sees the HID device creation event for some reason.
This is not an issue when starting the Toolbox as the USB device is already present, and detection of existing devices is done in `MainWindow_Load()` like so:
Thus, we should narrow down the query by specifically looking for USB devices, as we do in …
=> Fix BootloadHID devices not being detected automatically

osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/USB.cs
The [Pololu A-Star 32U4 Micro](https://www.pololu.com/product/3101) has its own flavour of Caterina with its own VID/PID pair.
*
=> Add support for Pololu A-Star

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
On macOS, attaching something to the `menu` outlet of a text box clobbers the existing context menu. Instead we should do it programmatically.
On Windows, it's a bit different. The RichTextBox control has no default right-click menu, so I think I'm going to opt for the standard Cut/Copy/Paste/Select All/sep/Clear, but with Cut and Paste greyed out for familarity.
Xcode also wanted to do some stuff...
*
=> Append clear menu item to existing menu

windows/QMK Toolbox/USB.cs
The bootloader from the Arduino LilyPad USB board, which uses USB VID:PID of `1b4f:9207`, can also be found on some 3.3V Pro Micro clones sold on AliExpress.
One particular board which can come with that bootloader version: https://www.aliexpress.com/item/32858541477.html **(WARNING: This board is not suitable as a Pro Micro replacement in most cases — the distance between rows of pins is 2.54mm (0.1″) larger than on a normal Pro Micro).** Similar 5V boards from the same seller, however, use the much more common `2341:0036` ID.
=> Add Caterina PID for LilyPad

osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
Discovered in #230. As it turns out, the USBTiny/AVR Pocket Programmer is not actually a USB serial device, so trying to pass a serial port to avrdude does not make much sense here and will cause it to fail/crash, at least on macOS.
*
=> Fix crash when flashing with USBTiny

osx/qmk_toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
For one thing, it's a little confusing, as some users seem to think it will list all connected QMK keyboards, regardless of whether Console is enabled.
For another, it's pointless - the dropdown already does the job of listing Console-enabled devices, and (IMO) in a much nicer way. Currently it does not do anything *other* than list the devices, but eventually I guess we would want to have it switch between console outputs, as was probably the idea originally.
*
=> Remove "List HID devices" button

windows/QMK Toolbox/MainWindow.cs
The .NET `Uri` class has trouble parsing the `\\wsl$` "hostname", because $ is not a valid character in a hostname.
See https://github.com/microsoft/WSL/issues/4722
Luckily, we don't need to try to parse the file path as a URI if we already know it starts with `\\wsl$`.
*
=> [Windows] Fix crash when using file picker to select firmware in WSL filesystem

osx/qmk_toolbox/USB.m
I forgot to also change these for the disconnect messages in #208. This leads to the connect messages saying eg. "Atmel DFU device connected", while the disconnect message says "AtmelDFU".
*
=> [macOS] Use passed friendly name for disconnect events

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/USB.m, osx/qmk_toolbox/main.m, readme.md, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs, windows/QMK Toolbox/USB.cs, windows/QMK Toolbox/drivers.txt
Add support for flashing APM32 via DFU.
These are pin compatible with STM32.
*
=> Add support for flashing APM32 via DFU

osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
Figured out how to grab the vendor and product strings/IDs, and a more reliable method of obtaining the callout device for Caterina by looping through all the serial devices and matching its parent device's VID/PID with the one that was just plugged in. No more "No modem port found"!
*
=> Bootloader detection refactor

readme.md
Updates the README.MD to reflect new way of installing homebrew casks.
To install a cask you no longer write `brew cask install package` but `brew install --cask package`.
This is now reflected in the README.MD.
=> Updates the README.MD to reflect new way of installing homebrew casks

osx/qmk_toolbox/AppDelegate.m, osx/qmk_toolbox/Base.lproj/MainMenu.xib, osx/qmk_toolbox/Flashing.h, osx/qmk_toolbox/Flashing.m, osx/qmk_toolbox/USB.m, windows/QMK Toolbox/App.config, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Properties/Settings.Designer.cs
* Fixes some UI inconsistencies surrounding enabling/disabling of the Flash, Exit DFU and Clear EEPROM buttons.
* Auto-flash now works again on macOS.
* Removed "Flash when ready" button on Windows. Seems to be a one-time autoflash? The remaining checkbox could potentially do double duty here, using the indeterminate state and clearing once a single flash is complete.
* Fixes #256
=> Autoflash improvements

osx/qmk_toolbox/USB.m, windows/QMK Toolbox/USB.cs
=> Add AT90USB162 to Atmel DFU PID arrays

osx/qmk_toolbox/USB.m, windows/QMK Toolbox/USB.cs
This is an attempt to fix a crash that occurs on macOS when the callout device does not appear within 0.5 seconds of the USB device. Instead of sleeping for that time, we just continually loop, under the assumption that a callout device *will* appear. I think this would be perfectly fine except that as far as I know this is running in the same thread as the UI - but that may be something for another day. It should not block for too long.
The logic is copied on the Windows side, although I think the COM port appears at the same time as the USB device anyway.
*
=> Serial port detection loop

windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/MainWindow.resx
- Added menu bar
- Removed status bar (now matches macOS; may reintroduce later if I find a good use for it)
- Cleaned up a bunch of control names
To be filled out later:
- Recent files menu (revert BetterComboBox)
- Implement options dialog, where one can configure flashing tool locations & arguments etc.
- Keytester under Tools menu (#41)
- USB device log under Tools menu (all devices, not just Console-enabled and bootloaders)
- Move Console stuff into separate dialog to avoid confusion?
*
=> [Windows] Add menu bar

osx/qmk_toolbox/Base.lproj/MainMenu.xib
The macOS end of #263.
- Added back some of the default menus
- Disabled tabbing
- Set minimum window size to 800x640 as in Windows; also now opens in center screen
- Made the titlebar transparent cause I thought it looked nice.
Will try to fix the constraint warnings in a followup PR.
The "Check for Updates" menu items here are disabled for now as I plan to implement Sparkle/WinSparkle, but it requires setting up the Xcode project to use Pods first, and setting up an update feed somewhere.
*
=> [macOS] Add menu bar

windows/QMK Toolbox/Helpers/EmbeddedResourceHelper.cs, windows/QMK Toolbox/MainWindow.cs
Make sure only single .hex, .bin and .qmk files get the drag-drop cursor. Also fix a problem from #270 where the resources weren't being extracted properly.
*
=> [Windows] Improve drag-drop events

.gitignore, macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox.xcodeproj/xcshareddata/xcschemes/QMK Toolbox.xcscheme, macos/QMK Toolbox/QMKWindow.m
#272, now the macOS side.
Also added gitignore rule for CocoaPods, in anticipation of getting Sparkle going at some point... plus fixed an issue with library search paths not liking spaces.
*
=> [macOS] Improve drag-drop events

macos/QMK Toolbox/QMKWindow.m
Turns out `NSFilenamesPboardType` is deprecated in favour of `NSPasteboardTypeFileURL`. I also removed the `containsObject` check as it seems the `registerForDraggedTypes` basically handles that.
*
=> [macOS] Fix deprecated pasteboard type

windows/QMK Toolbox/BetterComboBox.cs, windows/QMK Toolbox/ComboBoxPlaceholder.cs, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj
Hiding away the ugly `SendMessage()` in a subclass that can be reused for both boxes, because WinForms is dumb and doesn't come OOB with a placeholder text property...
*
=> [Windows] Subclass ComboBox for placeholder text

windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/USB.cs
The `ManagementEventWatcher` code has been moved into Usb.cs, and I've added a method to stop the watchers once the Toolbox is finished running. This will hopefully prevent "Quota violation" exceptions caused by (I think) the watchers continuing to run in the background and stopping the Toolbox from opening after some time.
*
=> [Windows] Improve USB device detection

windows/QMK Toolbox/QMK Toolbox.csproj, windows/QMK Toolbox/WindowState.cs
Found a slight bug immediately after merging #280 🤦 When toggling autoflash, the log box will print the "autoflash disabled/enabled" message again when you click away. Not sure why exactly that is, but it seems the solution is to simply compare the incoming value with the private field first.
https://www.codeproject.com/Questions/680120/bindingsource-property-setter-called-twice-why
Also, removed a dangling reference to `QMK Toolbox_TemporaryKey.pfx`, this seems to have something to do with ClickOnce which we are not using.
*
=> [Windows] Don't call OnPropertyChanged if property value is the same

macos/QMK Toolbox/Flashing.h, macos/QMK Toolbox/Flashing.m, macos/QMK Toolbox/USB.m, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/USB.cs
When the next qmk_firmware breaking changes cycle lands, with the updated LUFA submodule, the `:bootloader` target for a board with `BOOTLOADER = qmk-dfu` set will produce a .hex file that has it's USB device revision number set to `0x0936` (The Unicode codepoint for Ψ in decimal). This bootloader is able to clear the EEPROM without first performing a full chip erase.
*
=> Add QMK-DFU support

windows/QMK Toolbox.sln, windows/QMK Toolbox/AboutBox.Designer.cs, windows/QMK Toolbox/AboutBox.cs, windows/QMK Toolbox/Flashing.cs, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs
- Sorted usings
- Updated .sln file
- Removed more pointless `this`es (that VS flagged)
- Let VS reorganise the designer code
- Renamed click handlers etc. to appease VS
*
=> [Windows] Further cleanups

macos/QMK Toolbox/Base.lproj/MainMenu.xib, windows/QMK Toolbox/MainWindow.Designer.cs
A slight UI bug... the EEPROM menu should be completely disabled unless a bootloader device capable of modifying EEPROM contents is connected.
On macOS, the bindings for the handedness items also weren't set up.
*
=> Disable EEPROM menu if no compatible devices connected

windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj
Per https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls, the TLS versions should not be explicitly set, now that the project is at .NET 4.8.
Also removed some ClickOnce-related bootstrapper package includes; could reduce filesize a bit?
*
=> [Windows] Do not specify TLS version

macos/QMK Toolbox/Base.lproj/MainMenu.xib
Reordering UI elements in IB (no functional change), and redid the Auto Layout constraints which eliminated a few "fixed width" warnings.
Old (0.1.1):
New:
*
=> [macOS] UI cleanup

macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/Base.lproj/MainMenu.xib, macos/QMK Toolbox/KeyTester/Base.lproj/KeyTesterWindow.xib, macos/QMK Toolbox/KeyTester/Base.lproj/KeyView.xib, macos/QMK Toolbox/KeyTester/KeyTesterWindow.h, macos/QMK Toolbox/KeyTester/KeyTesterWindow.m, macos/QMK Toolbox/KeyTester/KeyView.h, macos/QMK Toolbox/KeyTester/KeyView.m, windows/QMK Toolbox/KeyTester/KeyControl.Designer.cs, windows/QMK Toolbox/KeyTester/KeyControl.cs, windows/QMK Toolbox/KeyTester/KeyControl.resx, windows/QMK Toolbox/KeyTester/KeyTesterWindow.Designer.cs, windows/QMK Toolbox/KeyTester/KeyTesterWindow.cs, windows/QMK Toolbox/KeyTester/KeyTesterWindow.resx, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj
Some mildly interesting notes on Windows:
- The VK value alone is not reliable enough as it changes based on the keyboard layout language. Thankfully, a PS/2 equivalent scancode is also provided, presumably for backward compatibility, or just vestigial
- Each KeyControl has to be set as disabled, as they apparently grab focus and prevent the key events from being intercepted by the form. Unfortunately this also changes the legend label text colour, and doesn't seem to be (easily) overrideable
Some mildly interesting notes on macOS:
- Caps Lock only generates flagsChanged events, as a result when caps lock is on the key is considered pressed.
- The Help (Insert) key doesn't generate a keyDown event
- There is no VK enum entry for the Application/Context menu key, but it is recognised
- F20 …
=> Add simple key tester

windows/QMK Toolbox/Helpers/DriverInstaller.cs
See the Wikipedia entry about Guard pattern: https://en.wikipedia.org/wiki/Guard_%28computer_science%29
Note that `!(a &&b)` is `(!a || !b)` and `YesNo` can only be `Yes` or `No`.
[source](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxbuttons?view=windowsdesktop-6.0)
I did not create any. This is just a small refactoring.
=> Use guard pattern

macos/QMK Toolbox/Base.lproj/MainMenu.xib
=> [macOS] UI updates

macos/QMK Toolbox/USB/USBListener.m
The wrong device class name was being sent back on M1 Macs, breaking detection.
This PR allows for either/or.
=> Fix up bootloader detection on M1 Macs.

windows/QMK Toolbox/MicrocontrollerSelector.cs
Having this in the constructor causes the code to be run, and then applied, whenever I make changes to the form, which adds stuff to the `.Designer.cs` and `.resx` files. Checking for `DesignMode` in the constructor also doesn't work, because... it's the constructor... so it needs to be done a bit later.
*
=> [Windows] Move MCU selector population code out of constructor

windows/QMK Toolbox/MainWindow.cs
I didn't remove enough code here... the `else` at the very end caused only WSL filepaths to be set. The null/empty check probably should also wrap everything, otherwise it could potentially cause a `UriFormatException`.
*
=> [Windows] Fix bug in SetFilePath()

macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/Base.lproj/MainMenu.xib
- `File->Open Recent->Clear` did not immediately clear the file path combobox
- `File->Open` threw an exception because the `openDocument:` method was not implemented - redirected it to `openButtonClick:`
* Fixes #77
Marking this as fixed because I think the "clear all" approach is better and simpler. Will need to be redone on Windows - there is no inbuilt functionality for it in WinForms.
=> [macOS] Fix open menu item and recent documents clear behaviour

macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/QMKWindow.m, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Program.cs
Untangling some spaghetti here. Now that the "keymap from qmk.fm" dropdown is gone, there is no need to do the whole change-file-extension-and-try-again stuff.
*
=> Refactor file handling

macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox/AppDelegate.m, macos/QMK Toolbox/USB/Bootloader/BootloaderType.h, macos/QMK Toolbox/USB/Bootloader/GD32VDFUDevice.h, macos/QMK Toolbox/USB/Bootloader/GD32VDFUDevice.m, macos/QMK Toolbox/USB/USBListener.m, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj, windows/QMK Toolbox/Resources/drivers.txt, windows/QMK Toolbox/Usb/Bootloader/BootloaderType.cs, windows/QMK Toolbox/Usb/Bootloader/Gd32VDfuDevice.cs, windows/QMK Toolbox/Usb/UsbListener.cs
=> Add GD32V bindings.

windows/QMK Toolbox/App.config
Updates the `App.config` file to opt in to high-DPI support as described in [this documentation](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8). It doesn't seem like it's necessary to add a manifest file to get this to work, so I didn't add one.
<details>
<summary>Before and after screenshots at 125% scaling</summary>
**Before**
**After**
</details>
=> [Windows] Enable high-DPI support

.github/workflows/build.yml
Code signs all the resources used by QMK Toolbox, builds QMK Toolbox, signs that, builds installer, then signs the installer.
* https://github.com/qmk/qmk_toolbox/issues/190
=> Add Windows code signing

.github/workflows/build.yml, macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox/QMK ToolboxRelease.entitlements, macos/certificate-setup.md
Adds signing and notarization for Mac app.
Sample result of release is here: https://github.com/nooges/qmk_toolbox/releases/tag/notarization-test-wb32
Replaces https://github.com/qmk/qmk_toolbox/pull/370 as source branch needed to be changed.
* https://github.com/qmk/qmk_toolbox/issues/227
=> Add signing and notarization for Mac app

macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox/AppDelegate.swift, macos/QMK Toolbox/Base.lproj/MainMenu.xib, macos/QMK Toolbox/HIDConsole/HIDConsoleWindow.swift, macos/QMK Toolbox/HIDConsole/HIDConsoleWindow.xib, macos/QMK Toolbox/KeyTester/Base.lproj/KeyTesterWindow.xib, windows/QMK Toolbox/HidConsole/HidConsoleWindow.Designer.cs, windows/QMK Toolbox/HidConsole/HidConsoleWindow.cs, windows/QMK Toolbox/HidConsole/HidConsoleWindow.resx, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/QMK Toolbox.csproj, windows/QMK Toolbox/Usb/Bootloader/LufaHidDevice.cs
=> Move HID console output to separate window

macos/QMK Toolbox.xcodeproj/project.pbxproj
The Toolbox itself does not need to link against these libraries.
This solves a rendering issue in Interface Builder for the custom KeyViews as the dylibs were marked as required but couldn't find them.
*
=> [macOS] Remove pointless linking to dylibs

.github/workflows/build.yml
Only sign binaries if we are doing a release, as signing secrets are unavailable for PRs, and signing binaries for PRs is not needed anyway.
*
=> Don't sign binaries for pull requests

readme.md
Per [this homebrew PR](https://github.com/Homebrew/homebrew-cask/pull/152603) which moved the cask thus breaking the existing command presented in the documentation. This PR fixes the homebrew command to alleviate any potential confusion.
#425
=> docs: update readme homebrew command

.github/workflows/build.yml, windows/QMK Toolbox/HidConsole/HidConsoleDevice.cs, windows/QMK Toolbox/QMK Toolbox.csproj, windows/install_compiler.iss
=> Build workflow: switch to `dotnet` and publish as self contained

readme.md
Having the $ in the code block makes Github's copy function useless, as it copies the $ also, causing terminals to error.
Removing the $ (while arguably it isn't as aesthetically pleasing) allows someone to copy and paste directly into their terminal.
=> Remove $ from brew download code block in README.md

windows/QMK Toolbox/Usb/UsbListener.cs
Apparently `HardwareID` can sometimes be null...
*
=> [Windows] Fix possible ArgumentNullException when enumerating USB devices

windows/QMK Toolbox/HidConsole/HidConsoleDevice.cs
Behaviour should now match that of macOS: https://github.com/qmk/qmk_toolbox/blob/master/macos/QMK%20Toolbox/HIDConsole/HIDConsoleDevice.swift#L53-L77
*
=> [Windows] Update HidDeviceReportEvent()

macos/QMK Toolbox/Info.plist, macos/QMK Toolbox/MainViewController.swift, macos/QMK Toolbox/USB/Bootloader/BootloaderDevice.swift, macos/QMK Toolbox/USB/Bootloader/LUFAMSDevice.swift, macos/QMK Toolbox/USB/USBListener.swift
* Opening files via double-click stopped working. Removing the NSDocumentClass value from the document types seems to fix it.
* `NSOpenPanel.allowedFileTypes` is deprecated as of macOS 12 - replace with `.allowedContentTypes`
*
=> [macOS] A couple of small bugfixes

windows/QMK Toolbox/HidConsole/HidConsoleWindow.cs
Tested on `handwired/onekey/proton_c:console`, the Toolbox crashes if the device sends a report after the HID Console window has closed.
*
=> [Windows] Fix HID Console crashing on close

windows/QMK Toolbox/HidConsole/HidConsoleWindow.Designer.cs, windows/QMK Toolbox/HidConsole/HidConsoleWindow.cs, windows/QMK Toolbox/HidConsole/HidConsoleWindow.resx, windows/QMK Toolbox/KeyTester/KeyControl.Designer.cs, windows/QMK Toolbox/KeyTester/KeyControl.resx, windows/QMK Toolbox/KeyTester/KeyTesterWindow.Designer.cs, windows/QMK Toolbox/KeyTester/KeyTesterWindow.cs, windows/QMK Toolbox/KeyTester/KeyTesterWindow.resx, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/MainWindow.resx
`FormStartPosition.CenterParent` doesn't work unless you show the window with `ShowDialog()`. Since we still want to allow interaction with the main window while they are open we have to use `Show()` instead and manually call `CenterToParent()` in the Load event handler.
And as usual Visual Studio wanted to move things around in the Designer.cs and resx files...
*
=> [Windows] Fix positioning for key tester and HID console windows

macos/QMK Toolbox.xcodeproj/project.pbxproj, macos/QMK Toolbox/HID/HIDConsoleDevice.swift, macos/QMK Toolbox/HID/HIDConsoleViewController.swift, macos/QMK Toolbox/HID/HIDDevice.swift, macos/QMK Toolbox/HID/HIDListener.swift, macos/QMK Toolbox/HID/RawDevice.swift, macos/QMK Toolbox/USB/USBListener.swift, windows/QMK Toolbox/Hid/BaseHidDevice.cs, windows/QMK Toolbox/Hid/HidConsoleDevice.cs, windows/QMK Toolbox/Hid/HidConsoleWindow.cs, windows/QMK Toolbox/Hid/HidListener.cs, windows/QMK Toolbox/Hid/RawDevice.cs
- Moved some common stuff out of the HID console device class
- Added HID device factory function to create either a console or raw instance based on usage page/usage
- Added necessary checks for console device report functionality
- Added raw HID stub (could be extended to attempt VIA version interrogation)
*
=> Add Raw HID device detection

windows/QMK Toolbox/Helpers/DriverInstaller.cs, windows/QMK Toolbox/Helpers/EmbeddedResourceHelper.cs, windows/QMK Toolbox/MainWindow.Designer.cs, windows/QMK Toolbox/MainWindow.cs, windows/QMK Toolbox/Usb/Bootloader/BootloaderDevice.cs
* Flashers are now extracted to `ProgramData` instead of versioned `AppData\Local`
* Folder is nuked on first run/Toolbox upgrade
* Added Tools menu item to force nuke the folder
*
=> [Windows] Improve embedded resource extraction behaviour

windows/QMK Toolbox/Hid/HidConsoleWindow.Designer.cs
- Hook up the `Opening` event  
- Hook up the `Copy`, `Select All`, and `Clear` actions  
- Remove the `Cut` and `Paste` actions
Ref https://github.com/qmk/qmk_firmware/pull/25175
=> [Windows] Fix context menu for HidConsole window

macos/QMK Toolbox/USB/USBListener.swift, windows/QMK Toolbox/Usb/UsbListener.cs
Apparently some people sell Pro Micro clones with a variant of the Caterina bootloader which shows up as `2A03:0040`; that VID:PID was originally used by the bootloader on the Arduino Leonardo ETH board. Add code to recognize that VID:PID combination as Caterina, so that those Pro Micro clones could be flashed.
Before the change the code treated the `0x2341` (Arduino SA) and `0x2A03` (dog hunter AG) VIDs identically; however, the `2341:0040` VID:PID pair apparently does not exist, therefore the code was changed to use separate branches for those VIDs and add only the `2A03:0040` combination.
* The bootloader on some Pro Micro clones is not recognized by QMK toolbox (the `2A03:0040` ID was reported in https://discord.com/channels/440868230475677696/867530222407778344/1355252043157078026 …
=> Recognize 2A03:0040 (Arduino Leonardo ETH) as a Caterina bootloader
